server:
  port: 8004

spring:
  application:
    name: auth-service
  config:
    import: configserver:http://localhost:8001

# Recovery Settings - Fail-safe if Config Server hasn't finished its Git clone
jwt:
  secret: SkillSyncSecretKey2026XyzAbc123SuperSecure!@#

info:
  app:
    name: SkillSync Auth Service
    version: 1.0.0
