server:
  port: 8006

spring:
  application:
    name: mentor-service
  config:
    import: optional:configserver:http://localhost:8001

# Service-specific details
info:
  app:
    name: SkillSync Mentor Service
    version: 1.0.0
