server:
  port: 8009

spring:
  application:
    name: group-service
  profiles:
    default: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8001}

# Service-specific details
info:
  app:
    name: SkillSync Group Service
    version: 1.0.0
