server:
  port: 8005

spring:
  application:
    name: user-service
  profiles:
    default: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8001}

# Service-specific details
info:
  app:
    name: SkillSync User Service
    version: 1.0.0
