server:
  port: 8001

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saisampath33/skillsync-config-repo
          clone-on-start: true
          default-label: main
          timeout: 20
          username: saisampath33
          password: ghp_YOUR_PERSONAL_ACCESS_TOKEN

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,bus-refresh
  endpoint:
    health:
      show-details: always

info:
  app:
    name: SkillSync Config Server
    version: 1.0.0
